version: "3.7"

services:
  backend:
    container_name: bosta-api-dev
    image: bosta-api-task:dev-v1
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@database:5432/library?schema=public
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: bash -c "chmod +x ./entrypoint.sh && ./entrypoint.sh --dev"
    ports:
      - 3000:3000
    networks:
      - local-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
