version: "3.7"

services:
  backend:
    container_name: bosta-api-dev
    image: bosta-api-task:dev-v1
    environment:
      DATABASE_URL: postgresql://postgres:example@database:5432/library?schema=public
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: bash -c "chmod +x ./entrypoint.sh && ./entrypoint.sh --dev --seed"
    ports:
      - 3000:3000
    networks:
      - local-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  pgadmin:
    user: root
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_CONFIG_SERVER_MODE=True
      - PGADMIN_DEFAULT_EMAIL=admin@hotmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    volumes:
      - ../data/pgadmin-backup/storage:/var/lib/pgadmin/storage
    networks:
      - local-network
